### YamlMime:ManagedReference
items:
- uid: Altv_Roleplay.Utils.Constants.DatabaseConfig
  commentId: T:Altv_Roleplay.Utils.Constants.DatabaseConfig
  id: Constants.DatabaseConfig
  parent: Altv_Roleplay.Utils
  children:
  - Altv_Roleplay.Utils.Constants.DatabaseConfig.Database
  - Altv_Roleplay.Utils.Constants.DatabaseConfig.Host
  - Altv_Roleplay.Utils.Constants.DatabaseConfig.Password
  - Altv_Roleplay.Utils.Constants.DatabaseConfig.Port
  - Altv_Roleplay.Utils.Constants.DatabaseConfig.User
  langs:
  - csharp
  - vb
  name: Constants.DatabaseConfig
  nameWithType: Constants.DatabaseConfig
  fullName: Altv_Roleplay.Utils.Constants.DatabaseConfig
  type: Class
  source:
    remote:
      path: Server/Altv-Roleplay/Utils/Constants.cs
      branch: master
      repo: https://xore@dev.azure.com/xore/Nightout-Gaming/_git/Nightout-Gaming
    id: DatabaseConfig
    path: Utils/Constants.cs
    startLine: 6
  assemblies:
  - NightOut-Gaming
  namespace: Altv_Roleplay.Utils
  syntax:
    content: public static class DatabaseConfig
    content.vb: Public Module DatabaseConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Altv_Roleplay.Utils.Constants.DatabaseConfig.Host
  commentId: F:Altv_Roleplay.Utils.Constants.DatabaseConfig.Host
  id: Host
  parent: Altv_Roleplay.Utils.Constants.DatabaseConfig
  langs:
  - csharp
  - vb
  name: Host
  nameWithType: Constants.DatabaseConfig.Host
  fullName: Altv_Roleplay.Utils.Constants.DatabaseConfig.Host
  type: Field
  source:
    remote:
      path: Server/Altv-Roleplay/Utils/Constants.cs
      branch: master
      repo: https://xore@dev.azure.com/xore/Nightout-Gaming/_git/Nightout-Gaming
    id: Host
    path: Utils/Constants.cs
    startLine: 11
  assemblies:
  - NightOut-Gaming
  namespace: Altv_Roleplay.Utils
  syntax:
    content: public static string Host
    return:
      type: System.String
    content.vb: Public Shared Host As String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Altv_Roleplay.Utils.Constants.DatabaseConfig.User
  commentId: F:Altv_Roleplay.Utils.Constants.DatabaseConfig.User
  id: User
  parent: Altv_Roleplay.Utils.Constants.DatabaseConfig
  langs:
  - csharp
  - vb
  name: User
  nameWithType: Constants.DatabaseConfig.User
  fullName: Altv_Roleplay.Utils.Constants.DatabaseConfig.User
  type: Field
  source:
    remote:
      path: Server/Altv-Roleplay/Utils/Constants.cs
      branch: master
      repo: https://xore@dev.azure.com/xore/Nightout-Gaming/_git/Nightout-Gaming
    id: User
    path: Utils/Constants.cs
    startLine: 12
  assemblies:
  - NightOut-Gaming
  namespace: Altv_Roleplay.Utils
  syntax:
    content: public static string User
    return:
      type: System.String
    content.vb: Public Shared User As String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Altv_Roleplay.Utils.Constants.DatabaseConfig.Password
  commentId: F:Altv_Roleplay.Utils.Constants.DatabaseConfig.Password
  id: Password
  parent: Altv_Roleplay.Utils.Constants.DatabaseConfig
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: Constants.DatabaseConfig.Password
  fullName: Altv_Roleplay.Utils.Constants.DatabaseConfig.Password
  type: Field
  source:
    remote:
      path: Server/Altv-Roleplay/Utils/Constants.cs
      branch: master
      repo: https://xore@dev.azure.com/xore/Nightout-Gaming/_git/Nightout-Gaming
    id: Password
    path: Utils/Constants.cs
    startLine: 13
  assemblies:
  - NightOut-Gaming
  namespace: Altv_Roleplay.Utils
  syntax:
    content: public static string Password
    return:
      type: System.String
    content.vb: Public Shared Password As String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Altv_Roleplay.Utils.Constants.DatabaseConfig.Port
  commentId: F:Altv_Roleplay.Utils.Constants.DatabaseConfig.Port
  id: Port
  parent: Altv_Roleplay.Utils.Constants.DatabaseConfig
  langs:
  - csharp
  - vb
  name: Port
  nameWithType: Constants.DatabaseConfig.Port
  fullName: Altv_Roleplay.Utils.Constants.DatabaseConfig.Port
  type: Field
  source:
    remote:
      path: Server/Altv-Roleplay/Utils/Constants.cs
      branch: master
      repo: https://xore@dev.azure.com/xore/Nightout-Gaming/_git/Nightout-Gaming
    id: Port
    path: Utils/Constants.cs
    startLine: 14
  assemblies:
  - NightOut-Gaming
  namespace: Altv_Roleplay.Utils
  syntax:
    content: public static string Port
    return:
      type: System.String
    content.vb: Public Shared Port As String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Altv_Roleplay.Utils.Constants.DatabaseConfig.Database
  commentId: F:Altv_Roleplay.Utils.Constants.DatabaseConfig.Database
  id: Database
  parent: Altv_Roleplay.Utils.Constants.DatabaseConfig
  langs:
  - csharp
  - vb
  name: Database
  nameWithType: Constants.DatabaseConfig.Database
  fullName: Altv_Roleplay.Utils.Constants.DatabaseConfig.Database
  type: Field
  source:
    remote:
      path: Server/Altv-Roleplay/Utils/Constants.cs
      branch: master
      repo: https://xore@dev.azure.com/xore/Nightout-Gaming/_git/Nightout-Gaming
    id: Database
    path: Utils/Constants.cs
    startLine: 15
  assemblies:
  - NightOut-Gaming
  namespace: Altv_Roleplay.Utils
  syntax:
    content: public static string Database
    return:
      type: System.String
    content.vb: Public Shared Database As String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Altv_Roleplay.Utils
  commentId: N:Altv_Roleplay.Utils
  name: Altv_Roleplay.Utils
  nameWithType: Altv_Roleplay.Utils
  fullName: Altv_Roleplay.Utils
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
