import * as alt from 'alt';
//ToDo: "requiredKey" Abfrage & "pickable" function
export const Doors = [{
        objName: 'hei_v_ilev_bk_gate2_pris',
        objCoords: new alt.Vector3(261.83, 221.39, 106.41),
        textCoords: new alt.Vector3(261.83, 221.39, 106.41),
        requiredKey: 'KEY',
        objYaw: -110.0,
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.5,
        size: 2,
    },
    //door2 for pacific opened with thermite right near the vault door
    {
        objName: 'hei_v_ilev_bk_safegate_pris',
        objCoords: new alt.Vector3(252.98, 220.65, 101.8),
        textCoords: new alt.Vector3(252.98, 220.65, 101.8),
        requiredKey: 'KEY',
        objYaw: 160.0,
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.5,
        size: 2,
    },
    // door3 for pacific opened with thermite after passing the door near vault
    {
        objName: 'hei_v_ilev_bk_safegate_pris',
        objCoords: new alt.Vector3(261.68, 215.62, 101.81),
        textCoords: new alt.Vector3(261.68, 215.62, 101.81),
        requiredKey: 'KEY',
        objYaw: -110.0,
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.5,
        size: 2,
    },
    // Paleto Door 1 opened with security card A
    {
        objName: 'v_ilev_cbankvaulgate01',
        objCoords: new alt.Vector3(-105.77, 6472.59, 31.81),
        textCoords: new alt.Vector3(-105.77, 6472.59, 31.81),
        objYaw: 45.0,
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.5,
        size: 2,
    },
    // Paleto Door 2 opened with thermite
    {
        objName: 'v_ilev_cbankvaulgate02',
        objCoords: new alt.Vector3(-106.26, 6476.01, 31.98),
        textCoords: new alt.Vector3(-105.5, 6475.08, 31.99),
        objYaw: -45.0,
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.5,
        size: 2,
    },
    // First Pacific Door opened with lockpick
    {
        objName: 'hei_v_ilev_bk_gate_pris',
        objCoords: new alt.Vector3(257.41, 220.25, 106.4),
        textCoords: new alt.Vector3(257.41, 220.25, 106.4),
        requiredKey: 'KEY',
        objYaw: -20.0,
        locking: false,
        locked: true,
        pickable: true,
        distance: 1.5,
        size: 2,
    },
    // Second Pacific Door opened with lockpick
    {
        objName: 'v_ilev_bk_door',
        objCoords: new alt.Vector3(265.19, 217.84, 110.28),
        textCoords: new alt.Vector3(265.19, 217.84, 110.28),
        requiredKey: 'KEY',
        objYaw: -20.0,
        locking: false,
        locked: true,
        pickable: true,
        distance: 1.5,
        size: 2,
    },
    // Fleeca Door opened with lockpick
    {
        objName: 'v_ilev_gb_vaubar',
        objCoords: new alt.Vector3(314.61, -285.82, 54.49),
        textCoords: new alt.Vector3(313.3, -285.45, 54.49),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: true,
        distance: 1.5,
        size: 2,
    },
    // Fleeca Door opened with lockpick
    {
        objName: 'v_ilev_gb_vaubar',
        objCoords: new alt.Vector3(148.96, -1047.12, 29.7),
        textCoords: new alt.Vector3(148.96, -1047.12, 29.7),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: true,
        distance: 1.5,
        size: 2,
    },
    // Fleeca Door opened with lockpick
    {
        objName: 'v_ilev_gb_vaubar',
        objCoords: new alt.Vector3(-351.7, -56.28, 49.38),
        textCoords: new alt.Vector3(-351.7, -56.28, 49.38),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: true,
        distance: 1.5,
        size: 2,
    },
    // Fleeca Door opened with lockpick
    {
        objName: 'v_ilev_gb_vaubar',
        objCoords: new alt.Vector3(-1208.12, -335.586, 37.759),
        textCoords: new alt.Vector3(-1208.12, -335.586, 37.759),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: true,
        distance: 1.5,
        size: 2,
    },
    // Fleeca Door opened with lockpick
    {
        objName: 'v_ilev_gb_vaubar',
        objCoords: new alt.Vector3(-2956.18, 483.96, 16.02),
        textCoords: new alt.Vector3(-2956.18, 483.96, 16.02),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: true,
        distance: 1.5,
        size: 2,
    },

    // Prison Door 1
    {
        objName: 'prop_gate_prison_01',
        objCoords: new alt.Vector3(1844.9, 2604.8, 44.6),
        textCoords: new alt.Vector3(1844.9, 2608.5, 48.0),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 13,
        size: 2,
    },
    // Prison Door 2
    {
        objName: 'prop_gate_prison_01',
        objCoords: new alt.Vector3(1818.5, 2604.8, 44.6),
        textCoords: new alt.Vector3(1818.5, 2608.4, 48.0),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 13,
        size: 2,
    },
    // Prison Door 3
    {
        objName: 'prop_gate_prison_01',
        objCoords: new alt.Vector3(1799.237, 2616.303, 44.6),
        textCoords: new alt.Vector3(1795.941, 2616.969, 48.0),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 10,
        size: 2,
    },
    // PD Storage Room
    {
        objName: 'v_ilev_ph_gendoor006',
        objCoords: new alt.Vector3(471.36, -985.63, 24.04),
        textCoords: new alt.Vector3(1795.941, 2616.969, 48.0),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 10,
        size: 2,
    },
    {
        textCoords: new alt.Vector3(434.81, -981.93, 30.89),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 2.5,
        doors: [{
                objName: 'v_ilev_ph_door01',
                objYaw: -90.0,
                objCoords: new alt.Vector3(434.7, -980.6, 30.8),
            },

            {
                objName: 'v_ilev_ph_door002',
                objYaw: -90.0,
                objCoords: new alt.Vector3(434.7, -983.2, 30.8),
            },
        ],
    },
    {
        objName: 'v_ilev_ph_gendoor004',
        objYaw: 90.0,
        objCoords: new alt.Vector3(450.13, -986.88, 30.69),
        textCoords: new alt.Vector3(450.13, -986.88, 30.69),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.5,
    },
    // Rooftop
    {
        objName: 'v_ilev_gtdoor02',
        objYaw: 90.0,
        objCoords: new alt.Vector3(464.3, -984.6, 43.8),
        textCoords: new alt.Vector3(464.38, -983.64, 43.8),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.5,
    },
    // Hallway to roof
    {
        objName: 'v_ilev_arm_secdoor',
        objYaw: 90.0,
        objCoords: new alt.Vector3(461.32, -986.38, 30.69),
        textCoords: new alt.Vector3(461.32, -986.38, 30.69),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.5,
    },
    // Armory
    {
        objName: 'v_ilev_arm_secdoor',
        objYaw: -90.0,
        objCoords: new alt.Vector3(452.6, -982.7, 30.6),
        textCoords: new alt.Vector3(452.95, -982.16, 30.99),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.5,
    },
    // Captain Office
    {
        objName: 'v_ilev_ph_gendoor002',
        objYaw: -180.0,
        objCoords: new alt.Vector3(447.72, -980.17, 30.81),
        textCoords: new alt.Vector3(447.72, -980.17, 30.81),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.5,
    },
    // To downstairs (double doors)
    {
        textCoords: new alt.Vector3(444.71, -989.43, 30.92),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 2.0,
        doors: [{
                objName: 'v_ilev_ph_gendoor005',
                objYaw: 180.0,
                objCoords: new alt.Vector3(443.9, -989.0, 30.6),
            },

            {
                objName: 'v_ilev_ph_gendoor005',
                objYaw: 0.0,
                objCoords: new alt.Vector3(445.3, -988.7, 30.6),
            },
        ],
    },
    // Mission Row Cells
    // Main Cells
    {
        objName: 'v_ilev_ph_cellgate',
        objYaw: 0.0,
        objCoords: new alt.Vector3(463.45, -992.6, 25.1),
        textCoords: new alt.Vector3(463.45, -992.6, 25.1),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.0,
    },
    // Cell 1
    {
        objName: 'v_ilev_ph_cellgate',
        objYaw: -90.0,
        objCoords: new alt.Vector3(461.89, -993.31, 25.13),
        textCoords: new alt.Vector3(461.89, -993.31, 25.13),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.0,
    },
    // Cell 2
    {
        objName: 'v_ilev_ph_cellgate',
        objYaw: 90.0,
        objCoords: new alt.Vector3(461.89, -998.81, 25.13),
        textCoords: new alt.Vector3(461.89, -998.81, 25.13),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.0,
    },
    // Cell 3
    {
        objName: 'v_ilev_ph_cellgate',
        objYaw: 90.0,
        objCoords: new alt.Vector3(461.89, -1002.44, 25.13),
        textCoords: new alt.Vector3(461.89, -1002.44, 25.13),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.0,
    },
    // To Back
    {
        objName: 'v_ilev_gtdoor',
        objYaw: 0.0,
        objCoords: new alt.Vector3(464.61, -1003.64, 24.98),
        textCoords: new alt.Vector3(464.61, -1003.64, 24.98),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 1.0,
    },
    // Mission Row Back
    // Back (double doors)
    {
        textCoords: new alt.Vector3(468.67, -1014.43, 26.48),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 2.5,
        doors: [{
                objName: 'v_ilev_rc_door2',
                objYaw: 0.0,
                objCoords: new alt.Vector3(467.3, -1014.4, 26.5),
            },

            {
                objName: 'v_ilev_rc_door2',
                objYaw: 180.0,
                objCoords: new alt.Vector3(469.9, -1014.4, 26.5),
            },
        ],
    },
    // Back Gate
    {
        objName: 'hei_prop_station_gate',
        objYaw: 90.0,
        objCoords: new alt.Vector3(488.8, -1017.2, 27.1),
        textCoords: new alt.Vector3(488.8, -1020.2, 30.0),
        requiredKey: 'KEY',
        locking: false,
        locked: true,
        pickable: false,
        distance: 20,
        size: 2,
    },
];